---
title: NACouncil
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: false
    read_time: false
    comments: false
    share: false
    related: false
email: 
description: North American Council for Anthroposophic and Curative Education
baseurl: 
url: 
markdown: kramdown
theme: minimal-mistakes-jekyll
plugins: 
breadcrumbs: false
include:
- _pages
