backend:
  name: github
  repo: CamphillOntario/nacouncil
  branch: master
media_folder: "assets/uploads/2017"
collections:
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Header", name: "header"}
      - {label: "Hero Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
